### ISSUE TITLE
myplanetdigital/secondlevel-scripts does not exist

### ISSUE THREAD

**Issue by mparker17** [oriuminc/secondlevel#1]
The `.gitmodules` file references a repository (`https://github.com/myplanetdigital/secondlevel-scripts.git`) which does not exist.

**Comment by patcon** [comment]
Ah hey, been working on the scripts submodule repo on other projects, and haven't been updating this as it's not in use yet.

This is the repo now, but no guarantees it's working with the base right now:
https://github.com/myplanetdigital/secondlevel-rerun-modules

We likely won't be able to keep this secondlevel profile working until we actually have a team/project with the time to slide it underneath a project install profile as the base. Otherwise it's going to languish and decay since it's not actively being used :)

**Comment by patcon** [comment]
PS, I'll fix this later though
